### PR TITLE
Numba support

### PR DESCRIPTION
**Pull request by RohanVardhan**
Allowing parallel computation of huge datasets using numba.

### CODE REVIEW

**Comment by MaxHalford** [comment]
Any progress?

**Comment by RohanVardhan** [comment]
Hi. Sorry to keep you waiting for so long. I haven't gotten a chance to fix the unit tests yet. But I am hoping to get on it this weekend and finalize it.

**Comment by MaxHalford** [comment]
No worries, take your time :). I prefer a job well done!

**Comment by RohanVardhan** [comment]
Hi @MaxHalford, I was checking the warning messages on travis. Apparently, numba does not support class definitions. Check it out [here](https://numba.pydata.org/numba-doc/dev/reference/pysupported.html).    That is why the test cases failed. I will think of some other way to parallelize the operations and let you know if I come up with a solution.

**Comment by MaxHalford** [comment]
Okay, I didn't know about that but it makes sense. Take your time!

**Comment by MaxHalford** [comment]
I'm closing this, but feel free to make another pull request if so inclined.

**Pull request closed without merging**
